language: cpp
compiler: g++
os: linux
sudo: false

cache:
  directories:
    - $HOME/.packman

before_install:
  - git clone https://github.com/dongli/packman
  - ./packman/setup.sh
  - source ./packman/bashrc
  - packman config -silent

install:
  - source $HOME/.packman/packman.bashrc
  - ls $HOME/.packman
  - echo "int main(void) { auto a = 1; }" > test.c
  - g++ -std=c++11 test.c
  - packman install gcc
