language: cpp
compiler: g++
os: linux

before_install:
    - sudo add-apt-repository -y "deb http://us.archive.ubuntu.com/ubuntu utopic main universe"
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq g++-4.8
    - sudo apt-get install -qq libxml2-dev
    - sudo apt-get install -qq libudunits2-dev
    - sudo apt-get install -qq libhdf5-dev
    - sudo apt-get install -qq libnetcdf-dev
    - sudo apt-get install -qq netcdf-bin
    - sudo apt-get install -qq libboost-date-time1.55-dev
    - sudo apt-get install -qq libboost-regex1.55-dev
    - sudo apt-get install -qq libboost-filesystem1.55-dev
    - sudo apt-get install -qq libboost-system1.55-dev
    - sudo apt-get install -qq libboost-timer1.55-dev
    - sudo apt-get install -qq libarmadillo-dev
    - sudo apt-get install -qq libmlpack-dev
    - export CC="gcc-4.8"
    - export CXX="g++-4.8"
    - export MLPACK_ROOT="/usr"

script:
    - cmake .
    - make -j 4
    - ./test_geomtk
