language: cpp
compiler: g++
os: linux
sudo: false

cache:
    directories:
        - $HOME/.packman

before_install:
	- git clone https://github.com/dongli/packman
	- ./packman/setup.sh
	- source $HOME/packman/bashrc
	- packman config -silent

install:
	- packman install gcc
